services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/.next
    command: npx next dev --turbopack
    restart: unless-stopped
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
